// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRFXWvc-YiZWYanUKlK1bjOlLNcqhQAfo',
    appId: '1:1025873769930:web:03abc0482ff477454b8b33',
    messagingSenderId: '1025873769930',
    projectId: 'alu-connect-13ded',
    authDomain: 'alu-connect-13ded.firebaseapp.com',
    storageBucket: 'alu-connect-13ded.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0A3xIRsR6HQ7hDIoVD6fcYKIItUokLEE',
    appId: '1:1025873769930:android:48fc33e2271c87fd4b8b33',
    messagingSenderId: '1025873769930',
    projectId: 'alu-connect-13ded',
    storageBucket: 'alu-connect-13ded.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0HWNkfqoJcdz9q5X73Lh5mqdtZegfKPA',
    appId: '1:1025873769930:ios:0247ba23061172d44b8b33',
    messagingSenderId: '1025873769930',
    projectId: 'alu-connect-13ded',
    storageBucket: 'alu-connect-13ded.firebasestorage.app',
    iosBundleId: 'com.example.aluConnect',
  );
}
